import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import organisationsRouter from "./organisations";
import projectsRouter from "./projects";
import wbsRouter from "./wbs";
import milestonesRouter from "./milestones";
import dprsRouter from "./dprs";
import photosRouter from "./photos";
import documentsRouter from "./documents";
import issuesRouter from "./issues";
import dashboardRouter from "./dashboard";
import approvalsRouter from "./approvals";
import estimationRouter from "./estimation";
import dsrRatesRouter from "./dsr-rates";
import rateSourcesRouter from "./rate-sources";
import variationOrdersRouter from "./variation-orders";
import financialRouter from "./financial";
import supplyChainRouter from "./supply-chain";
import workforceRouter from "./workforce";
import storageRouter from "./storage";
import geocodeRouter from "./geocode";
import modulesAccessRouter from "./modules-access";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import customRolesRouter from "./custom-roles";
import leadsRouter from "./leads";
import tendersRouter from "./tenders";
import customersRouter from "./customers";
import preEstimationsRouter from "./pre-estimations";
import quotationsRouter from "./quotations";
import statusHistoryRouter from "./status-history";
import invitationsRouter from "./invitations";
import subscriptionPlansRouter from "./subscription-plans";
import paymentsRouter from "./payments";
import adminPlatformRouter, { recordResponseTime } from "./admin-platform";
import { requireProjectAccess } from "../lib/access";

const router: IRouter = Router();

// ── Track response times for p95 metric ─────────────────────────────────────
router.use((_req, res, next) => {
  const start = Date.now();
  res.on("finish", () => recordResponseTime(Date.now() - start));
  next();
});

router.use((req, res, next) => {
  if (req.method === "OPTIONS") return next();
  const m = req.path.match(/^\/projects\/([^/?]+)(?:\/|$)/);
  if (!m) return next();
  (req as any).params = { ...(req.params || {}), projectId: m[1] };
  return requireProjectAccess()(req, res, next);
});

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(subscriptionPlansRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(customRolesRouter);
router.use(modulesAccessRouter);
router.use(reportsRouter);
router.use(organisationsRouter);
router.use(projectsRouter);
router.use(wbsRouter);
router.use(milestonesRouter);
router.use(dprsRouter);
router.use(photosRouter);
router.use(documentsRouter);
router.use(issuesRouter);
router.use(dashboardRouter);
router.use(approvalsRouter);
router.use(estimationRouter);
router.use(dsrRatesRouter);
router.use(rateSourcesRouter);
router.use(variationOrdersRouter);
router.use(financialRouter);
router.use(supplyChainRouter);
router.use(workforceRouter);
router.use(storageRouter);
router.use(geocodeRouter);
router.use(leadsRouter);
router.use(tendersRouter);
router.use(customersRouter);
router.use(preEstimationsRouter);
router.use(quotationsRouter);
router.use(statusHistoryRouter);
router.use(invitationsRouter);
router.use(adminPlatformRouter);

export default router;
